name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MoonBit CLI
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - name: Moon update
        run: moon update
      - name: Moon fmt
        run: moon fmt
      - name: Ensure fmt has no diff
        run: git diff --exit-code
      - name: Moon info
        run: moon info
      - name: Ensure info has no diff
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [js, native]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MoonBit CLI
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - name: Moon update
        run: moon update
      - name: Moon check
        run: moon check --deny-warn --target ${{ matrix.target }}
      - name: Moon test
        run: moon test --target ${{ matrix.target }}
